alias grub-install="grub-install --efi-directory=/efi"
alias grub-update="grub-mkconfig -o /boot/grub/grub.cfg"
alias l="eza -l -a -bhg --color=always --color-scale --group-directories-first --time-style=long-iso --git --extended"
alias b="bat -p"
alias c="clear"
alias e="exit"
alias watch-sensors="watch -n 1 sensors nvme-pci-0100 amdgpu-pci-0a00 zenpower-pci-00c3 it8686-isa-0a40"
alias watch-genlop="watch -cn 3 genlop -ci"
alias watch-free="watch -n 1 free -h"
alias clean-tmpfs="rm -rvf /var/tmp/portage/*"
alias make-clang="make LLVM=1 LLVM_IAS=1 -j14"
alias diff="/usr/bin/diff --color"
alias root="su -"
